model:
  name: 'resnet50_fc512'
  pretrained: True
  num_train_classes: 384 ### Preguntar a Jason
  load_weights: '/lynx-pie/wbia_pie_v2/models/pie_v2.snow_rc2.pth.tar'
  
data:
  type: 'image'
  source: 'iberianlynx'
  height: 300 ### Preguntar a Jason
  width: 300 ### Preguntar a Jason
  transforms_train: ['resize', 'random_crop', 'random_affine', 'random_flip']
  transforms_test: ['resize']
  version: 'v4_test3'

loss:
  name: 'triplet'
  triplet:
    weight_t: 1.
    weight_x: 1.
  softmax:
    label_smooth: True

sampler:
  num_instances: 4
  num_copies: 2

train:
  optim: 'adam'
  lr: 0.00001
  max_epoch: 1000
  batch_size: 16
  fixbase_epoch: 1
  open_layers: ['fc', 'classifier']
  lr_scheduler: 'multi_step'
  stepsize: [400]

test:
  batch_size: 16
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False
  ranks: [1, 5, 12, 20]
  visrank_topk: 12
  visrank_resize: False