model:
  name: 'efficientnet_b4'
  pretrained: True

data:
  type: 'image'
  source: 'iberianlynx'
  height: 128 ### Preguntar a Jason 
  width:  384 ### Preguntar a Jason 256 384
  transforms_train: ['resize', 'random_affine', 'blur', 'color_jitter','random_grayscale', 'random_flip'] #'random_crop',  'center_crop'
  transforms_test: ['resize']
  version: 'vt2v3_DArabcjrg_m001'

loss:
  name: 'triplet'
  triplet:
    weight_t: 1.
    weight_x: 1.
  softmax:
    label_smooth: True

sampler:
  num_instances: 3
  num_copies: 4

train:
  optim: 'adam'
  lr: 0.0001
  max_epoch: 1000
  batch_size: 64
  fixbase_epoch: 1
  open_layers: ['fc', 'classifier']
  lr_scheduler: 'multi_step'
  stepsize: [200]

test:
  batch_size: 64
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 5
  rerank: False
  ranks: [1, 5, 12, 20]
  visrank_topk: 12
  visrank_resize: False