model:
  name: 'resnet50_fc512'
  pretrained: True
  #num_train_classes: 384 ### Preguntar a Jason
  #load_weights: ''  # path to model weights

data:
  type: 'image'
  source: 'iberianlynx'
  workers: 2 
  height: 300 ### Preguntar a Jason
  width: 300 ### Preguntar a Jason
  k_tfm: 1 # number of times to apply augmentation to an image
  transforms_train: ['random_crop', 'random_affine', 'random_flip']
  #transforms_test: ['resize']
  version: 'v1'
  #save_dir: 'log' # path to save log

loss:
  name: 'triplet'
  triplet:
    weight_t: 1.
    weight_x: 1.
  softmax:
    label_smooth: True

sampler:
  num_instances: 3
  num_copies: 1

train:
  optim: 'adam'
  lr: 0.00001
  max_epoch: 1000
  batch_size: 16
  fixbase_epoch: 1
  open_layers: ['fc', 'classifier']
  lr_scheduler: 'multi_step'
  stepsize: [400]

test:
  batch_size: 16
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: 10
  rerank: False
  ranks: [1, 5, 12, 20]
  visrank_topk: 12
  visrank_resize: False